### PR TITLE
Update recipe for version 1.4

### PR DESCRIPTION
**Pull request by aradi**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

**Note**: Unfortunately, mpifx in its current form (also earlier versions) can not built with MPICH 4.x (see https://github.com/dftbplus/mpifx/issues/48).  Therefore, MPICH must be pinned accordingly. :disappointed:

### CODE REVIEW

**Comment by aradi** [comment]
@conda-forge-admin, please restart ci

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
OK, now, it seems to be OK. (I've pinned MPICH to version 3. We will remove it, once the type-mismatch had been fixed in upstream...)

**Review by bhourahine — APPROVED** [review]
LGTM

**Pull request merged**
